spring:
  application:
    name: spring-ai-mcp-client
  profiles:
    active: dev
  ai:
    vectorstore:
      redis:
        initialize-schema: true
        index-name: lee-vectorstore
        prefix: 'embedding:'
    openai:
      api-key: ${OPENAI_API_KEY}
      base-url: ${OPENAI_BASE_URL}
      chat:
        options:
          model: ${OPENAI_CHAT_OPTIONS_MODEL}
      embedding:
        options:
          model: text-embedding-v1
  data:
    redis:
      host: 127.0.0.1
      port: 9379
      password: 123456
  autoconfigure:
    exclude:
      - org.springframework.ai.model.transformers.autoconfigure.TransformersEmbeddingModelAutoConfiguration
